name: practica1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  avatar_glow:
  font_awesome_flutter:
  cupertino_icons: ^1.0.2
  provider:
  record:
  http:
  path_provider:
  url_launcher:
  firebase_core: ^2.2.0
  firebase_auth:
  google_sign_in:
  cloud_firestore:


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true